apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
spec:
  selector:
    matchLabels:
      app: go-web-app
  template:
    metadata:
      labels:
        app: go-web-app
    spec:
      containers:
      - name: go-container
        image: deepak25404/go-web-app:{{.Values.image.tag}}
        ports:
        - containerPort: 8080
