name: CI
on:
  push:
    branches:
      - main
    paths-ignore:
      - static/*
      - README.md
      - go-web-chart/*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'
    - name: Build
      run: go build -o go-web-app
    - name: Test
      run: go test -v ./...
  code-quality-analysis:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: GolangCI-Linter
      uses: Mushus/golangci-linter@v1.1.2
  build-push:
    runs-on: ubuntu-latest
    needs: code-quality-analysis
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push action
        uses: docker/build-push-action@v6
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{github.run_id}}
  update-helm-chart:
    needs: build-push
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUBTOKEN }}
    - name: Update tag in Helm chart
      run: |
        sed -i 's/tag: .*/tag: "${{github.run_id}}"/' go-web-chart/values.yaml
    - name: Commit and push changes
      run: |
        git config --global user.email "jitcse.deepaksingh@gmail.com"
        git config --global user.name "Deepak Singh Thakur"
        git add go-web-chart/values.yaml
        git commit -m "Update the new tag in Helm chart"
        git push
